#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jan 22 20:10:56 UZT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=MakeUp-UltraFast-9.4.zip
enableShaders=false
